services:
  backend:
    image: example/database
    volumes:
      - db-data:/etc/data

  backup:
    image: backup-service
    volumes:
      - db-data:/var/lib/backup/data

volumes:
  db-data:
    driver: local
    driver_opts:
      type: "btrfs"
      o: "o=size=1000m, uid=1026, gid=1000"